name: Monitorar Metrô SP

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # Permite rodar manualmente clicando no botão

jobs:
  vigia:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          pip install requests
          pip install cloudscraper

      - name: Rodar Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python monitor_metro_actions.py

      - name: Salvar dados
        run: |
          git config --global user.name 'Agente Metro Bot'
          git config --global user.email 'bot@noreply.github.com'
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Atualizando status [skip ci]"
            git push
          else
            echo "Sem mudanças"
          fi
